#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$ROOT/configuration/okd3/environment"

m '[manager] Ensuring ".kube/config" is up to date'

"$HERE/ansible" \
	--module-name fetch \
	--args "flat=true src=.kube/config dest=/home/manager/.kube/config" \
	masters[0]

m '[manager-root] Updating /etc/hosts for console.okd.lab'

PUBLIC_API_IP=$("$HERE/openstack" \
stack output show okd-cluster public_api_ip --format value --column output_value)

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	sed --in-place '/^.* console.okd.lab/d' /etc/hosts
	echo "$PUBLIC_API_IP console.okd.lab" >> /etc/hosts 

EOT
)"

m '[okd] Logging in as "system:admin"'

"$HERE/oc" \
login \
	--username=system:admin \
	--namespace=default \
	https://console.okd.lab:8443

m "[manager] Enabling local port 8443 for web console forwarded via ssh \"okd-web-console\""

"$ROOT/utils/ensure-ssh-config-forward" okd-web-console "$MANAGER_OFFICE_IP_ADDRESS" manager manager@manager 8443 console.okd.lab:8443

m '[orchestrator] Updating /etc/hosts for console.okd.lab'

sudo sed --in-place '/^.* console.okd.lab/d' /etc/hosts
echo "127.0.0.1 console.okd.lab" | sudo tee --append /etc/hosts 
