#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == '-c' ]; then
	"$HERE/clean"
fi

# See: https://github.com/openshift/openshift-ansible/tree/release-3.11/playbooks/openstack

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/okd3/ && rsync' \
	"$ROOT/configuration/overcloud/heat/templates/okd-tenant.yaml" \
	"$ROOT/configuration/overcloud/heat/templates/okd.yaml" \
	manager:/home/manager/workloads/okd3/

m '[openstack] Creating "okd-tenant" stack'
"$ROOT/openstack" \
stack create okd-tenant \
	--template /home/manager/workloads/okd3/okd-tenant.yaml \
	--wait -v

m '[openstack] Creating "okd" stack'
"$HERE/openstack" \
stack create okd \
	--template /home/manager/workloads/okd3/okd.yaml \
	--wait -v

m '[openstack] Fetching "okd" private key'

"$HERE/openstack" \
stack output show okd private-key --format value --column output_value \
	> "$KEYS_ROOT/okd"

chmod 600 "$KEYS_ROOT/okd"

"$ROOT/rsync" \
	"$KEYS_ROOT/okd" \
	manager:/home/manager/keys/

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/okd3/inventory/group_vars/ && rsync' \
	"$ROOT/configuration/okd3/all.yml" \
	"$ROOT/configuration/okd3/OSEv3.yml" \
	manager:/home/manager/workloads/okd3/inventory/group_vars/

"$ROOT/rsync" \
	"$ROOT/configuration/okd3/ansible.cfg" \
	manager:/home/manager/workloads/okd3/

# Using "-t" for color output in Ansible
"$ROOT/ssh" -t manager "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	cat > "\$HOME/workloads/okd3/inventory/local" <<- _EOT
		[local]
		#localhost ansible_python_interpreter=python3
	_EOT

EOT
)"

m '[manager] Deploying OKD cluster'

"$HERE/ansible-playbook" \
	/home/manager/workloads/okd3/openshift-ansible/playbooks/openstack/openshift-cluster/provision_install.yml \
	-v

m '[manager] Ensuring "oc" is installed'

"$HERE/ansible" \
	--module-name fetch \
	--args "flat=true src=/bin/oc dest=/home/manager/workloads/okd3/oc" \
	masters[0]

"$ROOT/ssh" manager "chmod +x \"\$HOME/workloads/okd3/oc\""
