#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == '-c' ]; then
	"$HERE/clean"
fi

# See: https://github.com/openshift/openshift-ansible/tree/release-3.11/playbooks/openstack

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/okd3/ && rsync' \
	"$ROOT/configuration/overcloud/heat/templates/okd-tenant.yaml" \
	"$ROOT/configuration/overcloud/heat/templates/okd.yaml" \
	manager:/home/manager/workloads/okd3/

m '[openstack] Creating "okd-tenant" stack'
"$ROOT/openstack" \
stack create okd-tenant \
	--template /home/manager/workloads/okd3/okd-tenant.yaml \
	--wait -v

m '[openstack] Creating "okd" stack'
"$HERE/openstack" \
stack create okd \
	--template /home/manager/workloads/okd3/okd.yaml \
	--wait -v

m '[openstack] Fetching "okd" private key'

"$HERE/openstack" \
stack output show okd private-key --format value --column output_value \
	> "$KEYS_ROOT/okd"

chmod 600 "$KEYS_ROOT/okd"

"$ROOT/rsync" \
	"$KEYS_ROOT/okd" \
	manager:/home/manager/keys/

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/okd3/inventory/group_vars/ && rsync' \
	"$ROOT/configuration/okd3/all.yml" \
	"$ROOT/configuration/okd3/OSEv3.yml" \
	manager:/home/manager/workloads/okd3/inventory/group_vars/

"$ROOT/rsync" \
	"$ROOT/configuration/okd3/ansible.cfg" \
	manager:/home/manager/workloads/okd3/

# -t for color output in Ansible
"$ROOT/ssh" -t manager "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	. "\$HOME/labrc"

	cat > "\$HOME/workloads/okd3/inventory/local" <<- _EOT
		[local]
		#localhost ansible_python_interpreter=python3
	_EOT

	# Note: The playbooks will try to run the "openstack" command, which we already installed for
	# Python 3 (they are in ~/.local/bin)

	m '[manager] Deploying OKD cluster'

	ROOT="\$HOME/workloads/okd3"

	PATH="\$PATH:\$HOME/.local/bin" \
	ANSIBLE_CONFIG="\$ROOT/ansible.cfg" \
	OPENSHIFT_CLUSTER=okd-cluster \
	OS_PROJECT_DOMAIN_NAME=okd \
	OS_PROJECT_NAME=okd \
	OS_USER_DOMAIN_NAME=okd \
	OS_USERNAME=okd-admin \
	OS_PASSWORD=password \
	ansible-playbook \
		--user openshift \
		--private-key "\$HOME/keys/okd" \
		--inventory "\$ROOT/openshift-ansible/playbooks/openstack/inventory.py" \
		--inventory "\$ROOT/inventory/" \
		"\$ROOT/openshift-ansible/playbooks/openstack/openshift-cluster/provision_install.yml" \
		-v

EOT
)"
