#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == -c ]; then
	"$HERE/clean"
fi

. "$ROOT/configuration/okd3/environment"

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	yum install --assumeyes \
		python-pip libselinux-python

	# CentOS's libselinux-python package is only for Python 2
	# Also note that it must be installed at system level, not user level
	pip install --upgrade \
		selinux==0.1.6

EOT
)"

# Using "-t" to improve wget display
"$ROOT/ssh" manager "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	# BUG: We need to use Python 2 because the playbooks are hardcoded to run the "python" command,
	# which on CentOS 7 is Python 2
	# See: https://github.com/openshift/openshift-ansible/issues/11820

	m '[manager] Ensuring Ansible is installed'
	pip install --user --upgrade \
		ansible==$(c "$ANSIBLE_VERSION") \
		shade==$(c "$SHADE_VERSION") \
		dnspython==$(c "$DNSPYTHON_VERSION")

	ROOT=\$HOME/workloads/okd3

	mkdir --parents "\$ROOT/"

	m '[manager] Ensuring OpenShift Ansible is installed'
	if [ ! -d "\$ROOT/openshift-ansible" ]; then
		git clone --branch="release-$OKD_VERSION" https://github.com/openshift/openshift-ansible.git "\$ROOT/openshift-ansible"
		#tag = "v$OKD_VERSION" # tag
	fi

	m '[manager] Ensuring "kubectl" is installed'
	if [ ! -f "\$ROOT/kubectl" ]; then
	 	wget \
	 		--output-document="\$ROOT/kubectl" \
	 		"https://storage.googleapis.com/kubernetes-release/release/v$KUBECTL_VERSION/bin/linux/amd64/kubectl"

		chmod +x "\$ROOT/kubectl"
	fi

	m '[manager] Updating PATH in ".bashrc"'
	sed --in-place "/# OKD3 START/,/# OKD3 END/d" "\$HOME/.bashrc"
	cat >> "\$HOME/.bashrc" <<- _EOT
		# OKD3 START
		PATH="\\\$PATH:\$ROOT"
		# OKD3 END
	_EOT

EOT
)"

"$HERE/patch"
