#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$ROOT/configuration/okd3/environment"

if [ "$1" == stop ]; then

	# See: https://stackoverflow.com/a/15198031
	"$ROOT/ssh" \
		-o ControlMaster=no \
		-S "$SSH_CONTROL_ROOT/okd-web-console" \
		-O exit \
		okd-web-console

else

	if ! grep --quiet "^127.0.0.1 console.okd.lab$" /etc/hosts; then
		m '[orchestrator] Updating /etc/hosts for console.okd.lab'
		sudo sed --in-place '/^.* console.okd.lab$/d' /etc/hosts
		echo "127.0.0.1 console.okd.lab" | sudo tee --append /etc/hosts
	fi 

	"$ROOT/ssh" -fN okd-web-console

	xdg-open https://console.okd.lab:8443/console/

fi
