#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == -c ]; then
	"$HERE/clean"
fi

# See: https://github.com/openshift/openshift-ansible/tree/release-3.11/playbooks/openstack

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/okd/ && rsync' \
	"$ROOT/configuration/okd/okd-tenant.yaml" \
	"$ROOT/configuration/okd/okd.yaml" \
	manager:/home/manager/workloads/okd/

m '[openstack] Creating "okd-tenant" stack'
"$ROOT/openstack" \
stack create okd-tenant \
	--template /home/manager/workloads/okd/okd-tenant.yaml \
	--wait -v

m '[openstack] Creating "okd" stack'
"$HERE/openstack" \
stack create okd \
	--template /home/manager/workloads/okd/okd.yaml \
	--wait -v

m '[openstack] Fetching "okd" private key'

"$HERE/openstack" \
stack output show okd private-key --format value --column output_value \
	> "$KEYS_ROOT/okd"

chmod 600 "$KEYS_ROOT/okd"

"$ROOT/rsync" \
	"$KEYS_ROOT/okd" \
	manager:/home/manager/keys/

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/okd/inventory/group_vars/ && rsync' \
	"$ROOT/configuration/okd/all.yml" \
	"$ROOT/configuration/okd/OSEv3.yml" \
	manager:/home/manager/workloads/okd/inventory/group_vars/

"$ROOT/rsync" \
	"$ROOT/configuration/okd/ansible.cfg" \
	manager:/home/manager/workloads/okd/

# Using "-t" for color output in Ansible
"$ROOT/ssh" -t manager "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	cat > "\$HOME/workloads/okd/inventory/local" <<- _EOT
		[local]
		#localhost ansible_python_interpreter=python3
	_EOT

EOT
)"

m '[manager] Deploying OKD cluster'

"$HERE/ansible-playbook" \
	/home/manager/workloads/okd/openshift-ansible/playbooks/openstack/openshift-cluster/provision_install.yml \
	-v

m '[manager] Ensuring "oc" is installed'

"$HERE/ansible" \
	--module-name fetch \
	--args "flat=true src=/bin/oc dest=/home/manager/workloads/okd/oc" \
	masters[0]

"$ROOT/ssh" manager "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	ROOT=\$HOME/workloads/okd

	chmod +x "\$ROOT/oc"

	m '[okd] Updating bash completion'

	mkdir --parents "\$HOME/.bash_completion.d/"
	"\$ROOT/oc" completion bash > "\$HOME/.bash_completion.d/oc"

EOT
)"
