#!/bin/bash
set -e

HOST=$1

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

m "[manager-root] Updating /etc/hosts for $HOST"

PUBLIC_ROUTER_IP=$("$ROOT/workloads/okd/openstack" \
stack output show okd-cluster public_router_ip --format value --column output_value)

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	sed --in-place '/^.* $HOST/d' /etc/hosts
	echo "$PUBLIC_ROUTER_IP $HOST" >> /etc/hosts 

EOT
)"
