#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$ROOT/configuration/onap/environment"

"$ROOT/workloads/okd/delete-tenant" "$OKD_USER" "$OKD_PROJECT"

m '[okd] Deleting persistent volumes'

function persistentvolume () {
	#"$ROOT/workloads/okd/oc" \
	#patch persistentvolume "$1" \
	#	--patch='{"spec":{"persistentVolumeReclaimPolicy":"Recycle"}}' || true

	# Note: If the persistentvolume uses hostPath, then that directory will not be deleted,
	# no matter what the reclaimPolicy is!
	"$ROOT/workloads/okd/oc" \
	delete persistentvolume "$1" --wait || true
}

persistentvolume mariadb-galera-mariadb-galera-data0
persistentvolume mariadb-galera-mariadb-galera-data1
persistentvolume mariadb-galera-mariadb-galera-data2

"$ROOT/workloads/okd/oc" \
adm policy reconcile-sccs \
	--additive-only=false --confirm
