#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == -c ]; then
	"$HERE/clean"
fi

. "$ROOT/configuration/onap/environment"

"$ROOT/workloads/okd/create-tenant" "$OKD_USER" "$OKD_PROJECT" scc:privileged cluster-role:cluster-admin

#	scc:anyuid scc:hostaccess scc:hostmount-anyuid scc:hostnetwork scc:nonroot scc:privileged \
#	cluster-role:cluster-admin

function deploy () {
	local COMPONENT=$1
	m "[helm] Deploying component \"$COMPONENT\""
	"$ROOT/workloads/helm/helm" install "local/$COMPONENT" \
		--name-template="$COMPONENT" \
		--namespace="$OKD_PROJECT" \
		--debug \
		"${@:2}"
}

deploy mariadb-galera --set persistence.enabled=false
deploy so
