#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == -c ]; then
	"$HERE/clean"
fi

. "$ROOT/configuration/onap/environment"

"$ROOT/workloads/helm3/create-tenant" "$OKD_USER" "$OKD_PROJECT"

function deploy () {
	COMPONENT=$1
	m "[helm] Deploying component \"$COMPONENT\""
	"$ROOT/workloads/helm3/helm" install "local/$COMPONENT" \
		--name-template="$HELM_TEMPLATE" \
		--namespace="$OKD_PROJECT" \
		--debug
}

deploy so
