#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$ROOT/configuration/helm/environment"
. "$ROOT/configuration/onap/environment"

# See: https://onap.readthedocs.io/en/latest/submodules/oom.git/docs/oom_quickstart_guide.html
# See: https://onap.readthedocs.io/en/latest/guides/onap-developer/settingup/index.html
# See: https://github.com/onap/oom
# See: https://github.com/onap/oom/blob/5.0.1-ONAP/docs/oom_quickstart_guide.rst

PATCH=$(cat "$ROOT/patches/onap/patch")

"$ROOT/ssh" manager "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	ROOT="\$HOME/workloads/onap"

	m '[manager] Ensuring ONAP OOM is installed'
	if [ ! -d "\$ROOT/oom" ]; then
		git clone --branch="$ONAP_VERSION" --recurse-submodules http://gerrit.onap.org/r/oom "\$ROOT/oom"
		echo $(c "$PATCH") > "\$ROOT/patch"
		chmod +x "\$ROOT/patch"
		"\$ROOT/patch" "$CHARTMUSEUM_PORT"
	fi

	m '[helm] Building ONAP charts'
	cd "\$ROOT/oom/kubernetes"
	make

EOT
)"
