#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$HERE
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

"$HERE/podman-bash" lab-controller-0 ceph-mgr-lab-controller-0 \
"ceph $(c "$@")"
