#!/bin/bash
set -e

HOST=$1

HERE=$(dirname "$(readlink -f "$0")")
. "$HERE/utils/functions"

"$HERE/ssh" "$HOST" \
"sudo ip netns exec \$(sudo ip netns list | cut --delimiter=' ' --fields=1) $(c "${@:2}")"
