#!/bin/bash
set -e

IMAGE_NAME=$1
DISK_SIZE=$2

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

EQ_IMAGE_NAME=$(eq "$IMAGE_NAME")
C_IMAGE_NAME=$(c "$IMAGE_NAME")
EQ_DISK_SIZE=$(eq "$DISK_SIZE")
C_DISK_SIZE=$(c "$DISK_SIZE")
C_BASE_IMAGE_URL=$(c "$CENTOS7_IMAGE")
C_BASE_IMAGE_NAME=$(c "/home/manager/libvirt/images/centos7.qcow2")

"$ROOT/ssh" manager-root -tt "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	if [ -f $C_IMAGE_NAME ]; then
		m "[manager-root] Virtual machine disk image already exists: \"$EQ_IMAGE_NAME\""
		exit
	fi

	if [ -f $C_BASE_IMAGE_NAME ]; then
		m "[manager-root] Base image already exists: \"$C_BASE_IMAGE_NAME\""
	else
		m "[manager-root] Downloading base image: \"$C_BASE_IMAGE_NAME\""
		mkdir --parents "\$(dirname $C_BASE_IMAGE_NAME)"
		wget --output-document=$C_BASE_IMAGE_NAME.xz $C_BASE_IMAGE_URL.xz
		xz --decompress $C_BASE_IMAGE_NAME.xz
	fi

	m "[manager-root] Creating virtual machine disk image: \"$EQ_IMAGE_NAME\" ($EQ_DISK_SIZE)"
	mkdir --parents \$(dirname $C_IMAGE_NAME)
	cp $C_BASE_IMAGE_NAME $C_IMAGE_NAME
	qemu-img resize $C_IMAGE_NAME $C_DISK_SIZE

EOT
)"
