#!/bin/bash
set -e

# Note: use "_" instead of "-" for NETWORK

NAME=$1
NETWORK=$2

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"

ADDRESSES=$("$HERE/openstack" server show "$NAME" --format value --column addresses | sed 's/\-/_/g')
eval "$ADDRESSES"
echo "${!NETWORK}"
