#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$HERE/environment"

"$ROOT/workloads/okd3/delete-tenant" "$OKD_USER" "$OKD_PROJECT"
