#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == -c ]; then
	"$HERE/clean"
fi

. "$HERE/environment"

"$ROOT/workloads/okd3/create-tenant" "$OKD_USER" "$OKD_PROJECT"

HOST=$OKD_APPLICATION-$OKD_PROJECT.apps.okd.lab

m "[helm] Deploying chart \"$OKD_HELM_CHART\""

"$HERE/../helm" \
install "$OKD_HELM_CHART" \
	--name-template="$OKD_HELM_TEMPLATE" \
	--namespace="$OKD_PROJECT"

m "[manager-root] Updating /etc/hosts for $HOST"

PUBLIC_ROUTER_IP=$("$ROOT/workloads/okd3/openstack" \
stack output show okd-cluster public_router_ip --format value --column output_value)

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	sed --in-place '/^.* $HOST/d' /etc/hosts
	echo "$PUBLIC_ROUTER_IP $HOST" >> /etc/hosts 

EOT
)"
