#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$HERE/environment"

HOST="$OKD_TEMPLATE-$OKD_PROJECT.apps.okd.lab"

m "[okd] Logging in as \"$OKD_USER\""

"$HERE/../oc" \
login --username="$OKD_USER" --password=doesntmatter

m "[okd] Deleting project \"$OKD_PROJECT\""

"$HERE/../oc" \
delete project "$OKD_PROJECT" || true

m '[okd] Logging in as "system:admin"'

"$HERE/../oc" \
login --username=system:admin --namespace=default

m "[okd] Deleting user \"$OKD_USER\""

"$HERE/../oc" \
delete user "$OKD_USER"

"$HERE/../oc" \
delete identity "allow_all:$OKD_USER"

m '[manager] Cleaning /etc/hosts'

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	sed --in-place '/^.* $HOST/d' /etc/hosts

EOT
)"
