#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$ROOT/configuration/okd3/hello-world/environment"

"$HERE/../delete-tenant" "$OKD_USER" "$OKD_PROJECT"

HOST=$OKD_APP_TEMPLATE-$OKD_PROJECT.apps.okd.lab

m '[manager-root] Cleaning /etc/hosts'

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	sed --in-place '/^.* $HOST/d' /etc/hosts

EOT
)"
