# See: https://docs.openstack.org/heat/stein/template_guide/

heat_template_version: 2018-08-31

description: >-
  OKD tenant stack

resources:

  domain:
    type: OS::Keystone::Domain
    properties:
      name: okd
      description: >-
        OKD domain

  project:
    type: OS::Keystone::Project
    properties:
      name: okd
      description: >-
        OKD project
      domain: { get_resource: domain }

  admin-user:
    type: OS::Keystone::User
    properties:
      name: okd-admin
      description: >-
        OKD administrator
      domain: { get_resource: domain }
      password: password
      roles:
      - project: { get_resource: project }
        role: admin
      default_project: { get_resource: project }
