# See: https://docs.openstack.org/heat/stein/template_guide/

heat_template_version: 2018-08-31

description: >-
  OKD stack

resources:

  keypair:
    # Exposed as output "private-key"
    type: OS::Nova::KeyPair
    properties:
      name: openshift
      save_private_key: true

outputs:

  private-key:
    description: Private key
    value: { get_attr: [ keypair, private_key ] }
