#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$ROOT/configuration/okd/hello-world/environment"

HOST=$OKD_APP_TEMPLATE-$OKD_PROJECT.apps.okd.lab

"$ROOT/ssh" manager "curl $(c $HOST)"
