#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == -c ]; then
	"$HERE/clean"
fi

. "$ROOT/configuration/okd/hello-world/environment"

"$HERE/../create-tenant" "$OKD_USER" "$OKD_PROJECT"

m "[okd] Deploying \"$OKD_APP_TEMPLATE\" template"

"$HERE/../oc" \
new-app --template="$OKD_APP_TEMPLATE"

"$HERE/../update-router-host" "$OKD_APP_TEMPLATE-$OKD_PROJECT.apps.okd.lab"
