#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-with-fetch-results"

m '[tripleo] Deleting overcloud (~ 10 minutes)'

"$ROOT/undercloud/openstack" \
overcloud delete "$TRIPLEO_OVERCLOUD_HEAT_STACK" \
	--yes

m '[tripleo] Cleaning nodes'

"$ROOT/undercloud/openstack" \
baremetal node manage computehci

"$ROOT/undercloud/openstack" \
overcloud node clean computehci

"$ROOT/undercloud/openstack" \
overcloud node provide computehci

m '[manager] Disconnecting dashboard'

"$ROOT/utils/delete-ssh-config" openstack-dashboard
