#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

m "[tripleo] Fetching infrastructure nodes access keypair"

"$ROOT/rsync" \
	tripleo:/home/tripleo/.ssh/id_rsa \
	"$KEYS_ROOT/tripleo"

"$ROOT/rsync" \
	tripleo:/home/tripleo/.ssh/id_rsa.pub \
	"$KEYS_ROOT/tripleo.pub"

for NAME in $("$ROOT/undercloud/openstack" server list --format value --column Name); do
	EQ_NAME=$(eq "$NAME")
	IP_ADDRESS=$("$ROOT/undercloud/get-ipv4-address" "$NAME" ctlplane)
	if [ -n "$IP_ADDRESS" ]; then
		m "[tripleo] Enabling ssh access to infrastructure server \"$EQ_NAME\" on ctlplane: $IP_ADDRESS"
		"$ROOT/utils/ensure-ssh-config-proxy" "$NAME" "$IP_ADDRESS" heat-admin tripleo tripleo
	else
		m "[tripleo] Infrastructure server \"$EQ_NAME\" does not have an IP address on ctlplane" "$RED"
	fi
done

m "[tripleo] Fetching OpenStack access credentials"

"$ROOT/rsync" \
	"tripleo:/home/tripleo/${TRIPLEO_OVERCLOUD_HEAT_STACK}rc" \
	"$WORKSPACE_ROOT/${TRIPLEO_OVERCLOUD_HEAT_STACK}rc"

"$ROOT/rsync" \
	"$WORKSPACE_ROOT/${TRIPLEO_OVERCLOUD_HEAT_STACK}rc" \
	"manager:/home/manager/${TRIPLEO_OVERCLOUD_HEAT_STACK}rc"

CONTROLLER_IP_ADDRESS=$("$ROOT/manager/get-ipv4-address" openstack-controller br-public)

if [ -z "$CONTROLLER_IP_ADDRESS" ]; then
	m '[manager] Controller does not have an IP address on public network' "$RED"
	exit 1
fi

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	m '[manager] Enabling IP route to External network via controller on public network'

	# TODO make permanent
	ip route del 10.0.0.0/24 || true
	ip route add 10.0.0.0/24 via $(c "$CONTROLLER_IP_ADDRESS") || true

EOT
)"

m '[orchestrator] Enabling IP route to Public network via Manager'

sudo ip route del 10.0.2.0/24 || true
sudo ip route add 10.0.2.0/24 via "$MANAGER_OFFICE_IP_ADDRESS"

m "[manager] Enabling dashboard port $OPENSTACK_LOCAL_DASHBOARD_PORT forwarded via ssh \"openstack-dashboard\""

. "$WORKSPACE_ROOT/${TRIPLEO_OVERCLOUD_HEAT_STACK}rc"

DASHBOARD_IP_ADDRESS=$(echo "$OS_AUTH_URL" | awk --field-separator [/:] '{print $4}')

"$ROOT/utils/ensure-ssh-config-forward" openstack-dashboard "$MANAGER_OFFICE_IP_ADDRESS" manager manager@manager "$OPENSTACK_LOCAL_DASHBOARD_PORT" "$DASHBOARD_IP_ADDRESS:80"
