#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

m "[tripleo] Fetching infrastructure servers access keypair"

"$ROOT/rsync" \
	tripleo:/home/tripleo/.ssh/id_rsa \
	"$KEYS_ROOT/tripleo"

"$ROOT/rsync" \
	tripleo:/home/tripleo/.ssh/id_rsa.pub \
	"$KEYS_ROOT/tripleo.pub"

for NAME in $("$ROOT/undercloud/openstack" server list --format value --column Name); do
	EQ_NAME=$(eq "$NAME")
	IP_ADDRESS=$("$ROOT/undercloud/get-ipv4-address" "$NAME" ctlplane)
	if [ -n "$IP_ADDRESS" ]; then
		m "[tripleo] Enabling ssh access to infrastructure server \"$EQ_NAME\" on ctlplane: $IP_ADDRESS"
		"$ROOT/utils/ensure-ssh-config-proxy" "$NAME" "$IP_ADDRESS" heat-admin tripleo tripleo
	else
		m "[tripleo] Infrastructure server \"$EQ_NAME\" does not have an IP address on ctlplane" "$RED"
		exit 1
	fi
done

CONTROLLER_IP_ADDRESS=$("$ROOT/manager/get-ipv4-address" openstack-controller br-public)

if [ -z "$CONTROLLER_IP_ADDRESS" ]; then
	m '[manager] Controller virtual machine does not have an IP address on public network' "$RED"
	exit 1
fi

C_CONTROLLER_IP_ADDRESS=$(c "$CONTROLLER_IP_ADDRESS")

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	m '[manager-root] Enabling IP route to External network via controller'
	# This is required for the Manager to access the overcloud, e.g. via the "openstack" command

	ip route del 10.0.0.0/24 || true
	ip route add 10.0.0.0/24 via $C_CONTROLLER_IP_ADDRESS dev public

	# Make permanent
	cat > /etc/sysconfig/network-scripts/route-public <<- _EOT
		10.0.0.0/24 via $C_CONTROLLER_IP_ADDRESS dev public
	_EOT
	rm --force /etc/sysconfig/network-scripts/route-public.bak

EOT
)"

m "[manager] Fetching OpenStack admin access credentials"
# This is required for the Manager to access the overcloud, e.g. via the "openstack" command

"$ROOT/rsync" \
	"tripleo:/home/tripleo/${OPENSTACK_NAME}rc" \
	"$WORKSPACE_ROOT/${OPENSTACK_NAME}rc"

"$ROOT/rsync" \
	"$WORKSPACE_ROOT/${OPENSTACK_NAME}rc" \
	"manager:/home/manager/${OPENSTACK_NAME}rc"

# TODO: enable multi-domain on dashboard
# https://www.ibm.com/support/knowledgecenter/en/SS4KMC_2.5.0.9/com.ibm.ico.doc_2.5/enableosdashboard.html

m "[manager] Enabling local port $OPENSTACK_LOCAL_DASHBOARD_PORT for dashboard forwarded via ssh host \"openstack-dashboard\""

. "$WORKSPACE_ROOT/${OPENSTACK_NAME}rc"

DASHBOARD_IP_ADDRESS=$(echo "$OS_AUTH_URL" | awk --field-separator [/:] '{print $4}')

"$ROOT/utils/ensure-ssh-config-forward" openstack-dashboard "$MANAGER_OFFICE_IP_ADDRESS" manager manager@manager "$OPENSTACK_LOCAL_DASHBOARD_PORT" "$DASHBOARD_IP_ADDRESS:80"
