#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-with-fetch-results"

# BUG: We need to deploy Octavia *after* deploying our overcloud
# See: https://bugzilla.redhat.com/show_bug.cgi?id=1736591

# BUG: The default "OctaviaGenerateCerts: true" will generate a length of 25, so we must override it
# See: https://bugzilla.redhat.com/show_bug.cgi?id=1723051
OCTAVIA_ENVIRONMENT_YAML=$(cat "$ROOT/configuration/overcloud/heat/environments/octavia.yaml" |
	PASSPHRASE=$(eq "$(random_password 32)") \
	envsubst)

HEAT_ENVIRONMENTS_OCTAVIA_YAML=$(cat "$ROOT/configuration/overcloud/heat-environments-octavia.yaml" |
	HOME=/home/tripleo \
	ENVIRONMENTS=/home/tripleo/overcloud/templates/environments \
	envsubst)

"$ROOT/ssh" tripleo "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	. "\$HOME/stackrc"

	OVERCLOUD="\$HOME/overcloud"
	TEMPLATES="\$OVERCLOUD/templates"
	INFRASTRUCTURE="\$HOME/infrastructure"

	m '[tripleo] Updating Heat environment for Octavia'
	echo $(c "$OCTAVIA_ENVIRONMENT_YAML") \
		> "\$TEMPLATES/environments/octavia.yaml"

	m '[tripleo] Updating Heat environment selection'
	echo $(c "$HEAT_ENVIRONMENTS_OCTAVIA_YAML") \
		> "\$OVERCLOUD/heat-environments-octavia.yaml"

	m '[tripleo] Deploying Octavia'
	openstack \
	overcloud deploy \
		--stack $(c "$TRIPLEO_OVERCLOUD_HEAT_STACK") \
		--templates "\$TEMPLATES/" \
		--networks-file "\$INFRASTRUCTURE/networks.yaml" \
		--roles-file "\$INFRASTRUCTURE/roles.yaml" \
		--answers-file "\$OVERCLOUD/heat-environments-octavia.yaml" \
		$(c "$TRIPLEO_VERBOSITY")

EOT
)"
