#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-with-fetch-results"

# BUG: We need to deploy Octavia separately *after* deploying our overcloud
# See: https://bugzilla.redhat.com/show_bug.cgi?id=1736591

OCTAVIA_ENVIRONMENT_YAML=$(cat "$ROOT/configuration/overcloud/heat/environments/octavia.yaml" |
	AMPHORA_IMAGE=/home/tripleo/images/amphora.qcow2 \
	envsubst)

HEAT_ENVIRONMENTS_AFTER_YAML=$(cat "$ROOT/configuration/overcloud/heat-environments-after.yaml" |
	ENVIRONMENTS=/home/tripleo/overcloud/templates/environments \
	envsubst)

"$ROOT/ssh" tripleo "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	. "\$HOME/stackrc"

	OVERCLOUD=\$HOME/overcloud
	TEMPLATES=\$OVERCLOUD/templates
	INFRASTRUCTURE=\$HOME/infrastructure

	m '[tripleo] Updating Heat environment for Octavia'
	echo $(c "$OCTAVIA_ENVIRONMENT_YAML") \
		> "\$TEMPLATES/environments/octavia.yaml"

	m '[tripleo] Updating Heat environment selection'
	echo $(c "$HEAT_ENVIRONMENTS_AFTER_YAML") \
		> "\$OVERCLOUD/heat-environments-after.yaml"

	m '[tripleo] Deploying Octavia'
	openstack \
	overcloud deploy \
		--stack $(c "$OPENSTACK_NAME") \
		--templates "\$TEMPLATES/" \
		--networks-file "\$INFRASTRUCTURE/networks.yaml" \
		--roles-file "\$INFRASTRUCTURE/roles.yaml" \
		--answers-file "\$OVERCLOUD/heat-environments-after.yaml" \
		$(c "$TRIPLEO_VERBOSITY")

EOT
)"
