#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$ROOT/configuration/helm3/hello-world/environment"

"$ROOT/ssh" manager "curl $HELM_TEMPLATE-$HELM_CHART-$OKD_PROJECT.apps.okd.lab/login"
