#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == '-c' ]; then
	"$HERE/okd3/clean"
	"$HERE/hello-world/clean"
	"$HERE/common/clean"
fi

"$HERE/common/deploy"
"$HERE/hello-world/deploy"
"$HERE/okd3/all"
