#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

m '[openstack] Deleting "hello-world" stack'
"$HERE/openstack" \
stack delete hello-world \
	--wait -v || true

m '[openstack] Disabling "hello-world" domain'
# Domain needs to be disabled in order to delete it
"$ROOT/openstack" \
domain set hello-world --disable -v || true

m '[openstack] Deleting "hello-world-tenant" stack'
"$ROOT/openstack" \
stack delete hello-world-tenant \
	--wait -v || true

"$ROOT/utils/delete-ssh-config" hello-world
