#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

HELLO_WORLD_IMAGE=centos7 # can also try "fedora"
HELLO_WORLD_USERNAME=admin

if [ "$1" == '-c' ]; then
	"$HERE/clean"
fi

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/hello-world/ && rsync' \
	"$ROOT/configuration/overcloud/heat/templates/hello-world-tenant.yaml" \
	"$ROOT/configuration/overcloud/heat/templates/hello-world.yaml" \
	manager:/home/manager/workloads/hello-world/

m '[openstack] Creating "hello-world-tenant" stack'
"$ROOT/openstack" \
stack create hello-world-tenant \
	--template /home/manager/workloads/hello-world/hello-world-tenant.yaml \
	--wait -v

m '[openstack] Creating "hello-world" stack'
"$HERE/openstack" \
stack create hello-world \
	--template /home/manager/workloads/hello-world/hello-world.yaml \
	--parameter "image=$HELLO_WORLD_IMAGE" \
	--parameter "username=$HELLO_WORLD_USERNAME" \
	--parameter "timezone=$TIMEZONE" \
	--wait -v

m '[openstack] Fetching "hello-world" private key'

KEY="$HELLO_WORLD_USERNAME@hello-world"

"$HERE/openstack" \
stack output show hello-world private-key --format value --column output_value \
	> "$KEYS_ROOT/$KEY"

chmod 600 "$KEYS_ROOT/$KEY"

IP_ADDRESS=$("$HERE/openstack" \
stack output show hello-world public-ip --format value --column output_value)

LB_IP_ADDRESS=$("$HERE/openstack" \
stack output show hello-world public-load-balancer-ip --format value --column output_value)

m "[openstack] \"hello-world\" server's public IP address: $IP_ADDRESS"
m "[openstack] \"hello-world\" load balancer's URL: http://$LB_IP_ADDRESS/"

"$ROOT/utils/ensure-ssh-config-proxy" hello-world "$IP_ADDRESS" "$HELLO_WORLD_USERNAME" "$KEY" lab-controller-0

m "To connect: $(c "$ROOT")/ssh hello-world"
