#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap-with-fetch-results"

if [ "$1" == -c ]; then
	"$HERE/clean"
fi

# Not needed anymore?
if [ "$TRIPLEO_PATCH" == true ]; then
	"$HERE/patch"
fi

EQ_OPENSTACK_VERSION_NAME=$(eq "$OPENSTACK_VERSION_NAME")
EQ_CEPH_VERSION=$(eq "$CEPH_VERSION_NAME")

echo $EQ_CEPH_VERSION

# Using "-t" to improve wget display
"$ROOT/ssh" -t tripleo "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	BASE_IMAGE_NAME=\$HOME/images/centos7.qcow2

	if [ ! -f "\$BASE_IMAGE_NAME" ]; then
		m "[tripleo] Downloading base image: \"\$BASE_IMAGE_NAME\""
		mkdir --parents "\$(dirname "\$BASE_IMAGE_NAME")"
		wget --output-document="\$BASE_IMAGE_NAME.xz" $(c "$CENTOS7_IMAGE.xz")
		xz --decompress "\$BASE_IMAGE_NAME.xz"
	fi

	. "\$HOME/stackrc"

	m '[tripleo] Ensuring infrastructure images are built (~ 5 minutes)'

	# Default configs are in: /usr/share/openstack-tripleo-common/image-yaml/

	if [ $(c "$TRIPLEO_PATCH") == true ]; then
		# Use patch
		export DIB_INSTALLTYPE_ironic_agent=source
		export DIB_REPOTYPE_ironic_agent=git
		export DIB_REPOLOCATION_ironic_agent="\$HOME/source/ironic-python-agent"
	fi

	DIB_YUM_REPO_CONF="/etc/yum.repos.d/delorean.repo /etc/yum.repos.d/delorean-$EQ_OPENSTACK_VERSION_NAME-testing.repo /etc/yum.repos.d/tripleo-centos-ceph-$EQ_CEPH_VERSION.repo" \
	DIB_LOCAL_IMAGE=\$BASE_IMAGE_NAME \
	openstack \
	overcloud image build \
		--output-directory "\$HOME/images/" \
		$(c "$TRIPLEO_VERBOSITY")

	m '[tripleo] Ensuring infrastructure images are uploaded'

	openstack \
	overcloud image upload \
		--image-path "\$HOME/images/" \
		--update-existing \
		$(c "$TRIPLEO_VERBOSITY")

EOT
)"

if [ -n "$CONTROLLER_VIRTUALBMC_PORT" ]; then
	"$ROOT/manager/create-virtual-machine" openstack-controller
	"$ROOT/manager/enable-virtual-machine-virtualbmc" openstack-controller "$CONTROLLER_VIRTUALBMC_PORT"
fi

if [ -n "$COMPUTE_VIRTUALBMC_PORT" ]; then
	"$ROOT/manager/create-virtual-machine" openstack-compute
	"$ROOT/manager/enable-virtual-machine-virtualbmc" openstack-compute "$COMPUTE_VIRTUALBMC_PORT"
fi
