#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$HERE/environment"

m "[okd] Logging in as \"$OKD_USER\""

"$HERE/../../oc" \
login --username="$OKD_USER" --password=doesntmatter

m "[okd] Deleting project \"$OKD_PROJECT\""

"$HERE/../../oc" \
delete project "$OKD_PROJECT" --wait=true || true

m '[okd] Logging in as "system:admin"'

"$HERE/../../oc" \
login --username=system:admin --namespace=default

m "[okd] Deleting user \"$OKD_USER\""

"$HERE/../../oc" \
delete user "$OKD_USER" --wait=true 

"$HERE/../../oc" \
delete identity "allow_all:$OKD_USER" --wait=true 
