#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

. "$HERE/environment"

HOST="$OKD_APPLICATION-$OKD_PROJECT.apps.okd.lab"

"$ROOT/ssh" manager "curl $(c $HOST)"
