#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../../../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == '-c' ]; then
	"$HERE/clean"
fi

. "$HERE/environment"

HOST="$OKD_APPLICATION-$OKD_PROJECT.apps.okd.lab"

m "[okd] Logging in as \"$OKD_USER\""

# Note: this will create both the user and an "allow_all:" identity
# The password does *not matter*, you can subsequently login with *any* password,
# even on the Web Console
"$HERE/../../oc" \
login --username="$OKD_USER" --password=doesntmatter

m "[okd] Creating project \"$OKD_PROJECT\""

"$HERE/../../oc" \
new-project "$OKD_PROJECT"

m "[helm] Deploying chart \"$OKD_HELM_CHART\""

"$HERE/../helm" \
install "$OKD_HELM_CHART" \
	--name-template=hello-world \
	--namespace="$OKD_PROJECT"

m "[manager-root] Updating /etc/hosts for $HOST"

PUBLIC_ROUTER_IP=$("$HERE/../../openstack" \
stack output show okd-cluster public_router_ip --format value --column output_value)

"$ROOT/ssh" manager-root "$(cat <<- EOT

	$SCRIPT_PREAMBLE

	sed --in-place '/^.* $HOST/d' /etc/hosts
	echo "$PUBLIC_ROUTER_IP $HOST" >> /etc/hosts 

EOT
)"
