# Apply Heat environments in order.
#
# Answers file for "openstack overcloud deploy".

environments:

# Define from where to fetch service container images
- "$ENVIRONMENTS/container-images.yaml"

# Request infrastructure nodes per each node role
- "$ENVIRONMENTS/roles.yaml"

# Neutron (networking)
# * Map node roles to our "heat/templates/networking.j2.yaml"
# * Import our "networks.yaml"
# * Create ports for each service of each node role on the networks defined above
- "$ENVIRONMENTS/neutron.yaml"
- "$ENVIRONMENTS/networking.yaml"
- "$ENVIRONMENTS/network-isolation.yaml"

# Nova (compute)
- "$ENVIRONMENTS/nova.yaml"

# Ceph (storage)
# See: http://docs.ceph.com/ceph-ansible/
#      https://docs.openstack.org/tripleo-docs/latest/install/advanced_deployment/ceph_config.html
- "$ENVIRONMENTS/ceph-ansible/ceph-ansible.yaml"
- "$ENVIRONMENTS/tuned-ceph-filestore-hci.yaml"
- "$ENVIRONMENTS/ceph.yaml"

# Octavia (LBaaS)
# - "$ENVIRONMENTS/services/octavia.yaml"
# - "$ENVIRONMENTS/octavia.yaml"
