#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ROOT=$(readlink -f "$HERE/../..")
. "$ROOT/configuration/environment"
. "$ROOT/utils/functions"
. "$ROOT/utils/trap"

if [ "$1" == -c ]; then
	"$HERE/clean"
fi

"$ROOT/rsync" \
	--rsync-path='mkdir --parents /home/manager/workloads/common/ && rsync' \
	"$ROOT/configuration/overcloud/heat/templates/common.yaml" \
	manager:/home/manager/workloads/common/

m '[openstack] Creating "common" stack'
"$ROOT/openstack" \
stack create common \
	--template /home/manager/workloads/common/common.yaml \
	--parameter "centos7-image-url=$CENTOS7_IMAGE" \
	--parameter "fedora-image-url=$FEDORA_IMAGE" \
	--parameter "fedora-image-version=$FEDORA_IMAGE_VERSION" \
	--wait -v
